const fs = require('fs');
const path = require('path');
const ruvector = require('ruvector');

/**
 * 🌪️ ARG VECTOR SEARCH
 * Task: Search for skills using real ONNX embeddings generated by Ruflo's engine.
 */
async function search() {
    const query = process.argv[2];
    if (!query) {
        console.error("Please provide a search query.");
        process.exit(1);
    }

    try {
        // Initialize the ONNX embedder
        await ruvector.initOnnxEmbedder();

        // Load the skills with vectors
        const vectorsPath = path.join(__dirname, '..', '..', 'graphify-out', 'universal_skills_with_vectors.json');
        if (!fs.existsSync(vectorsPath)) {
            console.error(`Vectors file not found at ${vectorsPath}. Please run the generator first.`);
            process.exit(1);
        }

        const skills = JSON.parse(fs.readFileSync(vectorsPath, 'utf8'));

        // Generate embedding for the query
        const queryResult = await ruvector.embed(query);
        const queryVector = queryResult.embedding;

        // Calculate cosine similarity for all skills
        const scoredSkills = skills.map(skill => {
            if (!skill.embedding) return { ...skill, score: 0 };
            
            // Use the cosineSimilarity function from ruvector if available, otherwise manual
            let score = 0;
            if (typeof ruvector.cosineSimilarity === 'function') {
                score = ruvector.cosineSimilarity(queryVector, skill.embedding);
            } else {
                // Manual cosine similarity fallback
                let dotProduct = 0;
                let normA = 0;
                let normB = 0;
                for (let i = 0; i < queryVector.length; i++) {
                    dotProduct += queryVector[i] * skill.embedding[i];
                    normA += queryVector[i] * queryVector[i];
                    normB += skill.embedding[i] * skill.embedding[i];
                }
                score = dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
            }

            return { ...skill, score };
        });

        // Sort by score (highest first)
        scoredSkills.sort((a, b) => b.score - a.score);

        // Print top 10 results
        console.log(`\n🎯 Top matches for: "${query}"`);
        scoredSkills.slice(0, 10).forEach((skill, i) => {
            console.log(`${i + 1}. [${(skill.score * 100).toFixed(1)}%] ${skill.name} (⭐ ${skill.stars})`);
            console.log(`   ${skill.description}`);
            console.log(`   Path: ${skill.path}\n`);
        });

    } catch (error) {
        console.error("Error during search:", error);
    }
}

search().catch(console.error);
